version: '3'

services:
  nginx:
    container_name: pw_local_env-nginx_proyecto
    image: nginx:1.19.6-alpine
    restart: unless-stopped
    ports:
      - "8031:80"
    volumes:
      - .:/app
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    container_name: pw_local_env-php_proyecto
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9031:9001"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: pw_local_env-db_proyecto
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3331:3306"
    env_file:
      - .env

  admin:
    container_name: pw_local_env-admin_proyecto
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

